--liquibase formatted sql

--changeset codex:001-create-events context:gateway
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id VARCHAR(80) NOT NULL,
    account_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) DEFAULT 'RECEIVED' NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT uk_events_event_id UNIQUE (event_id),
    CONSTRAINT chk_events_event_id_alphanumeric CHECK (event_id REGEXP '^[A-Za-z0-9]{8,80}$'),
    CONSTRAINT chk_events_account_id_alphanumeric CHECK (account_id REGEXP '^[A-Za-z0-9]{8,80}$'),
    CONSTRAINT chk_events_type CHECK (event_type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT chk_events_status CHECK (status IN ('RECEIVED', 'APPLIED', 'FAILED')),
    CONSTRAINT chk_events_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_events_currency CHECK (currency REGEXP '^[A-Z]{3}$')
);

--changeset codex:002-create-events-account-time-index context:gateway
CREATE INDEX idx_events_account_timestamp
    ON events (account_id, event_timestamp);

--changeset codex:003-create-event-metadata context:gateway
CREATE TABLE event_metadata (
    event_pk BIGINT NOT NULL,
    metadata_key VARCHAR(120) NOT NULL,
    metadata_value VARCHAR(1000),
    CONSTRAINT pk_event_metadata PRIMARY KEY (event_pk, metadata_key),
    CONSTRAINT fk_event_metadata_event FOREIGN KEY (event_pk)
        REFERENCES events (id)
        ON DELETE CASCADE
);
