--liquibase formatted sql

--changeset codex:004-create-accounts context:account
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id VARCHAR(80) NOT NULL,
    balance DECIMAL(19, 4) DEFAULT 0 NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT uk_accounts_account_id UNIQUE (account_id),
    CONSTRAINT chk_accounts_account_id_alphanumeric CHECK (account_id REGEXP '^[A-Za-z0-9]{8,80}$'),
    CONSTRAINT chk_accounts_currency CHECK (currency REGEXP '^[A-Z]{3}$')
);

--changeset codex:005-create-account-transactions context:account
CREATE TABLE account_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id VARCHAR(80) NOT NULL,
    account_id VARCHAR(80) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_account_transactions PRIMARY KEY (id),
    CONSTRAINT uk_account_transactions_event_id UNIQUE (event_id),
    CONSTRAINT fk_account_transactions_account FOREIGN KEY (account_id)
        REFERENCES accounts (account_id),
    CONSTRAINT chk_account_transactions_event_id_alphanumeric CHECK (event_id REGEXP '^[A-Za-z0-9]{8,80}$'),
    CONSTRAINT chk_account_transactions_account_id_alphanumeric CHECK (account_id REGEXP '^[A-Za-z0-9]{8,80}$'),
    CONSTRAINT chk_account_transactions_type CHECK (transaction_type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT chk_account_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_account_transactions_currency CHECK (currency REGEXP '^[A-Z]{3}$')
);

--changeset codex:006-create-account-transactions-account-time-index context:account
CREATE INDEX idx_account_transactions_account_time
    ON account_transactions (account_id, event_timestamp);
